import Head from "next/head"
import { Footer } from "./Footer"
import { Header } from "./Header"
import { Aura } from "./Aura"

type Props = {
  preview?: boolean
  children: React.ReactNode
}

const Layout = ({ preview, children }: Props) => {
  return (
    <>
      <Head>
        <title>Whimsy</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="aura flex min-h-screen flex-col items-center bg-gradient-to-b  from-[#2e026dFF] to-[#15162c]">
        <div className="max-w-6xl w-screen mx-auto px-4 py-16">
          {children}
        </div>
      </main>
      <Footer />
    </>
  )
}

export default Layout